apiVersion: v1
kind: Pod
metadata:
  name: kubectl-role-pod
  namespace: default
  labels:
    app: kubectl
spec:
  containers:
  - name: kubectl
    image: nkkim/kubectl:1.0
    imagePullPolicy: Always
  serviceAccountName: sa-role-test

