apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-ready
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        args:
        - sleep 200 & /docker-entrypoint.sh nginx -g 'daemon off;'
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 1
          successThreshold: 1
          timeoutSeconds: 10 
          periodSeconds: 50
        
