apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-required
spec:
  selector:
    matchLabels:
      app: nginx
      type: required
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        type: required
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - dia01
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


