apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-preferred
spec:
  selector:
    matchLabels:
      app: nginx
      type: preferred
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        type: preferred
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - dia01
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

