apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  labels:
    app: kubectl
spec:
  containers:
  - name: kubectl
    image: nkkim/kubectl:1.0
    imagePullPolicy: Always
  - name: nginx
    image: nginx
  serviceAccountName: sa-test

